language: python
python:
    - '2.7'

# command to install dependencies
install:
    - pip install -r test_requirements.txt --use-mirrors
    - pip install . --use-mirrors

# command to run tests
script:
    - py.test
